name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc tcl python3 default-jdk maven

      - name: Run bootstrap.sh
        run: ./bootstrap.sh

      - name: Configure project
        run: ./configure

      - name: Build server and client
        run: make

      - name: Build Java client with Maven
        run: |
          cd java_client
          ./make_source_for_mvn.sh
          mvn clean
          mvn install

      - name: Run tests
        run: |
          if ls test_* 2>/dev/null; then
            pytest
          else
            echo "No tests found. Skipping."
